[package]
name = "reqwest_dav"
version = "0.1.1"
edition = "2021"
description = "An async webdav client with tokio and reqwest"
license = "MIT"
repository = "https://github.com/niuhuan/reqwest_dav"

[dependencies]
digest_auth = "0.3"
reqwest = "0.11"
url = "2.3"
tokio = { version = "1.22", features = ["rt-multi-thread", "macros", "fs", "sync", "time"] }
http = "0.2"
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.6"
serde_json = "1.0"
async-trait = "0.1"

[dev-dependencies]

